#!/bin/sh
set -e
### BEGIN INIT INFO
# Provides:          test
# Required-Start:    $all
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: init script for testing purposes
### END INIT INFO

echo Dependency test success: the test script is running $1
